### ISSUE TITLE
setup snapshot or otherwise publish

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-ui#10]
I'd like to make a docker image from the contents of this repo as opposed to running npm https://github.com/openzipkin/docker-zipkin-ui/issues/1

This will make it easier for others to test this code. What's the best path forward?

**Comment by adriancole** [comment]
we could have a mechanism to do normal npm, too. ex like https://github.com/openzipkin/zipkin-js has..

We could also setup a maven job and bintray for "io.zipkin.ui:zipkin-ui". This would allow those using zipkin-server to replace the ui they are using by swapping "io.zipkin.java:zipkin-ui" for "io.zipkin.ui:zipkin-ui"

we "might" even be able to recruit the same build tag to do both. @abesto wdyt?

**Comment by tonyhb** [comment]
+1 that would be awesome

**Comment by adriancole** [comment]
I'm going to go ahead and set this up using the process we use today. that will help us move forward in a way that can be used in the existing zipkin server

**Comment by adriancole** [comment]
I setup this and gave @rogeralsing access https://bintray.com/openzipkin/maven/zipkin-ui

I'll setup the build process next, copying what @llinder did for zipkin-aws

**Comment by adriancole** [comment]
ok next step is to switch circleci to use the new build (which still runs npm and tests)

**Comment by adriancole** [comment]
ok build is now switched.. next step make sure snapshot works 

http://oss.jfrog.org/oss-snapshot-local/io/zipkin/ui/

**Comment by adriancole** [comment]
ok that worked.

**Comment by adriancole** [comment]
creating a test release

```bash
$ git tag release-0.0.1
$ git push origin release-0.0.1
```

Will check circleci and also bintray after to make sure it works ok
https://circleci.com/gh/openzipkin/zipkin-ui
https://bintray.com/openzipkin/maven/zipkin-ui

**Comment by adriancole** [comment]
last step https://github.com/openzipkin/docker-zipkin/issues/130

**Comment by adriancole** [comment]
done
