### ISSUE TITLE
setup travis or circleci

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-ui#7]
would be nice if travis or circleci checked pull requests cc @abesto 

https://circleci.com/gh/openzipkin/zipkin-ui/1

**Comment by rogeralsing** [comment]
The problem might be related to NPM version:
To update `npm install -g npm`

Similar problem is described here: https://github.com/AngularClass/angular2-webpack-starter/issues/501

**Comment by abesto** [comment]
Have some good progress in https://github.com/abesto/zipkin-ui/tree/circleci. Currently I'm getting strange test failures, also getting the same ones locally: https://circleci.com/gh/abesto/zipkin-ui/7

Other than that, I'm ready for a PR, probably. One question first: how do y'all feel about https://coveralls.io/ for coverage reporting? They have badges, they have graphs. The branch currently includes integration with it, but I'm not married to the idea.

**Comment by abesto** [comment]
Oh. Note: the generated HTML for the coverage report can be found under the Artifacts tab (points to something like this: https://7-68402609-gh.circle-artifacts.com/0//tmp/circle-artifacts.rrvNswX/coverage/PhantomJS/index.html)

**Comment by adriancole** [comment]
don't mind about coverage.

tools that yell at you for pendantic things that might not make sense (like
codacy) would be something I'd feel more strongly about.

**Comment by adriancole** [comment]
setup now!
